version: 1
formatters:
  Formatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'
handlers:
  fileHandler:
    class: logging.FileHandler
    level: INFO
    formatter: Formatter
    filename: ../log.log
  streamHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: Formatter
    stream: ext://sys.stdout
loggers:
  logger:
    level: DEBUG
    handlers: [fileHandler, streamHandler]
    propagate: no
root:
  level: DEBUG
  handlers: []
